Modified installer, helper script template
Binds 2600:1700:xxx0:xxx0::1/128 to WAN interface for full
IPv6 connectivity from router, changes to verbiage etc.

diff --git a/install-attnative6 b/install-attnative6
--- a/install-attnative6
+++ b/install-attnative6
@@ -3,7 +3,7 @@
 # Description: Script to generate and install a configuration file for the
 #    dibbler DHCPv6 client and a helper script, intended for use on routers
 #    connected to u-Verse Fiber with the Residential Gateway bypassed.
-#    Results in native IPv6 via a DHCPv6 IA_NA and PD assignment.
+#    Results in native IPv6 with Prefix Delegation.
 # Requires: dibbler-client, template files in current directory
 # Template file names: client.conf.template, pdsplit.sh.template
 err() { echo "$*" >&2; }
@@ -11,25 +11,36 @@ die() { err "EXIT WITH ERROR: $*"; exit 1; }
 # this awk one-liner should be fully portable
 ascii2hex() { echo "$*" | awk 'BEGIN{for(n=0;n<256;n++)ord[sprintf("%c",n)]=n}{len=split($0,c,"");for(i=1;i<=len;i++)printf("%X",ord[c[i]])}'; }
 
+confirm() {
+  read -p "	Enter 'yes' exactly to confirm: " ans
+  [ "$ans" = "yes" ] && return 0 || return 1
+}
+
 conftmpl=client.conf.template
 hlptmpl=pdsplit.sh.template
 
 [ -x "$(which dibbler-client)" ] || die "dibbler-client not installed"
 [ "$(whoami)" = "root" ] || err "WARNING: NOT RUNNING AS ROOT"
-for f in $conftmpl $hlptmpl; do	[ -f $f ] || die "$f not found in current directory"; done
+for f in $conftmpl $hlptmpl; do  [ -f $f ] || die "$f not found in current directory"; done
 
 cat << EOF
-This script generates and installs configuration files for the dibbler DHCPv6
-client that configure it to receive an IA_NA (semi-permanent public IPv6
-address) and a PD (Prefix Delegation).
+
+This installer generates and installs configuration files for the dibbler DHCPv6
+client that configure it to request a global unicast address ("public", semi-
+permanent IPv6 address) and a Prefix Delegation (PD) very similarly to an Arris
+Motorola NVG599.
 
 This allows native dual-stack IPv6 connectivity on a router connected to a
 u-Verse Fiber ONT, either directly or via a managed switch, bypassing an RG.
 
-See https://is.gd/wokixe for more details.
+See https://is.gd/wokixe for more details on the bypass process.
+
+See https://github.com/kangtastic/attnative6 for more details on this installer.
 
 NOTE: This script is best run BEFORE STARTING dibbler-client FOR THE FIRST TIME.
 dibbler seems to ignore certain changes to its configuration otherwise.
+
+(If you are just trying to generate a new helper script, disregard this note.)
 
 Step 1) Interfaces
 Enter the names of the WAN-facing and LAN-facing interfaces on this system.
@@ -37,20 +48,24 @@ If bypassing using an EAP proxy, the WAN-facing interface is probably named
 something like "eth0.0".
 
 EOF
-while read -p "  WAN interface name: " wan; do [ -n "$wan" ] && break; done
-while read -p "  LAN interface name: " lan; do [ -n "$lan" ] && break; done
+while read -p "	WAN interface name: " wan; do [ -n "$wan" ] && break; done
+while read -p "	LAN interface name: " lan; do [ -n "$lan" ] && break; done
 
 cat << EOF
 
 Step 2) RG Information
 Enter your Residential Gateway's manufacturer and serial number.
+If the serial number contains any capital/small letters, enter them exactly.
 From this we can reconstruct the DUID-EN it sends during DHCPv6 requests.
 
+(If you are just trying to generate a new helper script, it doesn't matter what
+you enter here.)
+
 EOF
-while read -p "  Manufacturer [1=Pace, 2=Motorola]: " mfg; do
-	([ "$mfg" = "1" ] || [ "$mfg" = "2" ]) && break
+while read -p "	Manufacturer [1=Pace, 2=Motorola]: " mfg; do
+  ([ "$mfg" = "1" ] || [ "$mfg" = "2" ]) && break
 done
-while read -p "  Serial number: " serial; do [ -n "$serial" ] && break; done
+while read -p "	Serial number: " serial; do [ -n "$serial" ] && break; done
 
 cat << EOF
 
@@ -68,84 +83,127 @@ helper script will save its logs, you can do so now.
 Just press ENTER to accept the defaults.
 
 EOF
-read -p "  dibbler config directory [default=/etc/dibbler]: " confpath
-read -p "  Helper script directory [default=/etc/dibbler]: " hlppath
-read -p "  Helper script log directory [default=/var/log/dibbler]: " logpath
+read -p "	dibbler config directory [default=/etc/dibbler]: " confpath
+read -p "	Helper script directory [default=/etc/dibbler]: " hlppath
+read -p "	Helper script log directory [default=/var/log/dibbler]: " logpath
 [ -z "$confpath" ] && confpath=/etc/dibbler
 [ -z "$hlppath" ] && hlppath=/etc/dibbler
 [ -z "$logpath" ] && logpath=/var/log/dibbler
 
 cat << EOF
 
-Step 4) Confirm
-Please confirm that the information below is correct, or the script will quit.
+Step 4) WAN interface PD address assignment
+Many have noticed that the address that AT&T gives you on the WAN interface
+doesn't actually give you IPv6, but addresses in the Prefix Delegation work
+fine.
+
+It turns out that AT&T hasn't turned on routing on their end for the entire
+range of IPv6 addresses from which they are handing out IPv6 assignments to
+router WAN interfaces! They could at some future point, but haven't yet.
+
+The logical workaround involves binding a single address from the same subnet
+being used on the LAN to the WAN interface.
+
+Insert this workaround into the helper script?
 
 EOF
-echo "    WAN interface: $wan"
-echo "    LAN interface: $lan"
-echo
-echo "    RG manufacturer: $([ $mfg = 1 ] && echo Pace || echo Motorola)"
-echo "    RG serial number: $serial"
-echo
-echo "    dibbler configuration file directory: $confpath"
-echo "    Helper script directory: $hlppath"
-echo "    Helper script log directory: $logpath"
-echo
-read -p "  Enter 'yes' exactly to confirm: " ans
-[ "$ans" = "yes" ] || die "User canceled"
+bindwan=no; confirm && bindwan=yes
 
 cat << EOF
 
-Step 5) Generate and install
-We will try to generate a new configuration for the dibbler client, close any
-running instances of the client, and replace dibbler's current configuration.
+Step 5) Confirm
+Please confirm that the information below is correct, or the script will quit.
+
+EOF
+echo "	WAN interface: $wan"
+echo "	LAN interface: $lan"
+echo
+echo "	RG manufacturer: $([ $mfg = 1 ] && echo Pace || echo Motorola)"
+echo "	RG serial number: $serial"
+echo
+echo "	Additional address on WAN interface from PD: $bindwan"
+echo
+echo "	dibbler configuration file directory: $confpath"
+echo "	Helper script directory: $hlppath"
+echo "	Helper script log directory: $logpath"
+echo
+confirm || die "User canceled"
+
+conf=$(echo $conftmpl | sed 's|.template||')
+hlp=$(echo $hlptmpl | sed 's|.template||')
+
+cat << EOF
+
+Step 6) Generate and install
+We will try to generate a new configuration for dibbler-client, close any
+running instances, delete the client's current lease database, and install the
+generated configuration file and helper script.
+
+(If you are just trying to generate a new helper script, don't delete the lease
+database and don't install client.conf.)
 
 EOF
 [ "$mfg" = "1" ] && mfg="00D09E" || mfg="001E46"
 duiden=$(ascii2hex "$mfg-$serial"); duiden="0x$duiden"
 
 for f in $conftmpl $hlptmpl; do
-	of=$(echo $f | sed 's|.template||')
-	cp $f $of &&
-	sed -e "s|__DATE__|$(date -R)|" -i.bak $of &&
-	sed -e "s|__WAN__|$wan|" -i.bak $of &&
-	sed -e "s|__LAN__|$lan|" -i.bak $of &&
-	sed -e "s|__DUIDEN__|$duiden|" -i.bak $of &&
-	sed -e "s|__CONFPATH__|$confpath|" -i.bak $of &&
-	sed -e "s|__HLPPATH__|$hlppath|" -i.bak $of &&
-	sed -e "s|__LOGPATH__|$logpath|" -i.bak $of &&
-	rm $of.bak &&
-	echo "$of generated." || die "$of could not be generated."
+  of=$(echo $f | sed 's|.template||')
+  cp $f $of &&
+  sed -s "s|__INSTALLERPATH__|$(readlink -f $0)|" -i.bak $of &&
+  sed -e "s|__DATE__|$(date -R)|" -i.bak $of &&
+  sed -e "s|__WAN__|$wan|" -i.bak $of &&
+  sed -e "s|__LAN__|$lan|" -i.bak $of &&
+  sed -e "s|__DUIDEN__|$duiden|" -i.bak $of &&
+  sed -e "s|__CONFPATH__|$confpath|" -i.bak $of &&
+  sed -e "s|__HLPPATH__|$hlppath|" -i.bak $of &&
+  sed -e "s|__LOGPATH__|$logpath|" -i.bak $of &&
+  sed -e "s|__BINDWAN__|$bindwan|" -i.bak $of &&
+  rm $of.bak &&
+  echo "	$of generated." || die "	$of could not be generated."
 done
 echo
 
 if [ -n "$(pgrep dibbler-client)" ]; then
-	echo "dibbler client is running, killing it now."
-	killall dibbler-client || err "Could not kill dibbler client!"
-	echo
+  echo "dibbler-client is running, killing it now."
+  echo "This should also release the DHCPv6 assignments it has, if any."
+  killall dibbler-client || err "Could not kill dibbler-client!"
+  echo
 fi
 if [ -f /var/lib/dibbler/client-duid ]; then
-	echo "Would you like to clear dibbler client's current configuration?"
-	echo "It seems that you have run it before, so this is probably necessary."
-	read -p "  Enter 'yes' exactly to confirm: " ans
-	if [ "$ans" = "yes" ]; then
-		rm -f /var/lib/dibbler/client* || err "Failed, are you root?"
-	fi
-	echo
+cat << EOF
+Clear dibbler-client's DHCPv6 lease database? It seems you've run it already.
+This is probably necessary, unless you already have IPv6 (possibly through this
+installer script).
+
+Technical reason: If dibbler-client has already generated a DUID-LLT from your
+MAC address, it stores it in the lease database, even without any leases, and
+ignores a DUID-EN configured in client.conf.
+
+EOF
+  if confirm; then
+    rm -f /var/lib/dibbler/client* || err "Failed, are you root?"
+  fi
+  echo
 fi
-conf=$(echo $conftmpl | sed 's|.template||')
-echo "Would you like to install $conf into $confpath?"
-read -p "  Enter 'yes' exactly to confirm: " ans
-if [ "$ans" = "yes" ]; then
-	mkdir -p "$confpath" && mv $conf "$confpath" || err "Failed, are you root?"
+
+echo "Install $conf (the config file) into $confpath?"
+echo
+if confirm; then
+  mkdir -p "$confpath" && mv $conf "$confpath" || err "Failed, are you root?"
 fi
 echo
-hlp=$(echo $hlptmpl | sed 's|.template||')
+
 chmod +x $hlp
-echo "Would you like to install $hlp into $hlppath?"
-read -p "  Enter 'yes' exactly to confirm: " ans
-if [ "$ans" = "yes" ]; then
-	mkdir -p "$ hlppath" && mv $hlp "$hlppath" || err "Failed, are you root?"
-fi
+echo "Install $hlp (the helper script) into $hlppath?"
 echo
-echo "Finished."
+if confirm; then
+  mkdir -p "$ hlppath" && mv $hlp "$hlppath" || err "Failed, are you root?"
+fi
+
+cat << EOF
+
+Step 7) Finished.
+
+Run 'systemctl restart dibbler-client' as root to start or restart the client.
+
+EOF
diff --git a/pdsplit.sh.template b/pdsplit.sh.template
--- a/pdsplit.sh.template
+++ b/pdsplit.sh.template
@@ -1,85 +1,123 @@
 #!/bin/sh
 # File: __HLPPATH__/pdsplit.sh
-# Description: Helper for dibbler-client to split a delegated /64 or shorter
-#     by binding the first /64 within to a LAN interface. Also tries to set a
-#     default IPv6 route.
-# Generated on:  __DATE__
+# Generated by __INSTALLERPATH__ on: __DATE__
 #
-# This script should be called by dibbler-client after it has received an IA_NA
-# and a delegated prefix from a DHCPv6 server. It relies on environment
-# variables available when it is called this way and will not work otherwise.
+# Description: Helper for dibbler-client to split a delegated /64 or shorter.
+#   Binds the first address in the first /64 subnet within the PD to a LAN
+#   interface. May bind the second address in the first /64 to a WAN interface.
+#   Also tries to set a default IPv6 route.
 #
-# IPv6 connectivity for LAN clients requires, at minimum, sending Router
-# Advertisements (with radvd/dnsmasq) to the LAN interface and enabling IPv6
-# forwarding in the kernel. An ip6tables firewall is also a very good idea.
+#   This script should be called by dibbler-client after it has received an
+#   address and a prefix delegation. It relies on environment variables
+#   available when it is called this way and will not work otherwise.
+#
+#   IPv6 connectivity for LAN clients requires, at a minimum, sending Router
+#   Advertisements (with radvd/dnsmasq) to the LAN interface and enabling IPv6
+#   forwarding in the kernel. An ip6tables firewall is also a very good idea.
 #
 # Recommended: rdisc6 (ICMPv6 Router Discovery tool, Debian package name ndisc6)
 
 # LAN interface to which the PD should be bound
 LAN=__LAN__
 
+# Bind $PREFIX1::1 to WAN interface?
+BINDWAN=__BINDWAN__
+
 script=$(basename $0)
 logpath="__LOGPATH__"; mkdir -p "$logpath"
 logfile="$logpath/$(basename $script .sh).log"
 reason=manual; [ -n "$1" ] && reason=$1
 
-log() { echo "$(date '+%Y.%m.%d %T') $script $*" >> "$logfile"; }
-die() {	log "EXIT WITH ERROR: $*"; exit 1; }
+# DEBUG: Uncomment the 3 lines below, restart dibbler-client, & check the .dbg
+#   file for cmdline, cmdline args, & environment variables at script runtime.
+# dbg="/tmp/pdsplit.dbg"
+# echo $(for arg in "$0" "$@"; do echo -n "'$arg' "; done; echo; echo) > $dbg
+# env 2>&1 >> $dbg
+
+log() {
+  msg="$1";
+  [ "$2" = "1" ] && msg="$msg unnecessary, moving on"
+
+  [ "$2" = "2" ] && msg="$msg succeeded"
+  echo -n "$(date '+%Y.%m.%d %T') $script $msg" >> "$logfile"
+  echo >> "$logfile"
+}
+die() { log "EXIT WITH ERROR: $*"; exit 1; }
 
 log "started, reason: $reason"
 
-[ "$reason" = "manual" ] && die "should only be called by dibbler-client"
-[ $PREFIX1LEN -gt 64 ] && die "received prefix longer than a /64"
 [ -x "$(which ip)" ] || die "ip utility from iproute2 not found"
+[ "$reason" = "manual" ] && die "should only be called by dibbler-client"
+[ $PREFIX1LEN -le 64 ] && GUA64="$PREFIX1/64" && GUA128="${PREFIX1}1/128" ||
+  die "received prefix longer than a /64"
 
-# If $PREFIX1/64 not bound to LAN, purge all other global IPv6 addrs and add it
-replace_global_addr() {
-	if ip -6 -br addr show dev $LAN | grep -q $PREFIX1/64; then
-		log "LAN interface $LAN already bound to $PREFIX1/64, moving on"
-	else
-		log "binding $PREFIX1/64 to LAN interface $LAN"
-		ip -6 addr flush dev $LAN scope global &&
-		ip -6 addr add $PREFIX1/64 dev $LAN || die "failed"
-	fi
+# If 2600:1700:xxx0:xxx0::/64 is not bound to LAN, purge all other global
+# unicast addresses and add it.
+replace_lan_gua() {
+  msg="binding $GUA64 to LAN interface $LAN"
+  if ip -6 -br addr show dev $LAN | grep -q $LAN $GUA64; then
+    log "$msg" 1
+  else
+    ip -6 addr flush dev $LAN scope global &&
+    ip -6 addr add $GUA64 $LAN && log "$msg" 2 || die "$msg"
+  fi
+}
+# If 2600:1700:xxx0:xxx0::1/128 is not bound to WAN, add it.
+add_wan_gua() {
+  msg="binding $GUA128 to WAN interface $IFACE"
+  if ip -6 -br addr show dev $IFACE | grep -q $GUA128; then
+    log "$msg" 1
+  else
+    ip -6 addr add $GUA128 $IFACE && log "$msg" 2 || die "$msg"
+  fi
 }
 fixup_default_route() {
-	cur_gateway=$(ip -6 route show default | awk '{print $3}')
-	adv_gateway=$(rdisc6 -n $IFACE | tail -1 | awk '{print $2}')
-	# Running rdisc6 should just refresh the default route, but may
-	# be adding a new one entirely. If it's the latter, purge & rerun
-	if [ "$cur_gateway" = "$adv_gateway" ]; then
-		log "no problem with default route, moving on"
-	else
-		log "purging and readding default route"
-		ip -6 route flush default &&
-		rdisc6 -n $IFACE 2>&1 1>/dev/null || die "failed"
-	fi
-	log "default IPv6 route is via $adv_gateway on dev $IFACE"
+  old_gateway=$(ip -6 route show default | awk '{print $3}')
+  new_gateway=$(rdisc6 -n $IFACE | tail -1 | awk '{print $2}')
+  # Running rdisc6 should just refresh the default route. If it added a new one
+  # entirely, purge the new default route & rerun rdisc6 to be extra thorough
+  msg="purging and readding default route"
+  if [ "$old_gateway" = "$new_gateway" ]; then
+    log "$msg" 1
+  else
+    ip -6 route flush default &&
+    rdisc6 -n $IFACE 2>&1 1>/dev/null && log "$msg" 2 || die "failed"
+  fi
+  log "default IPv6 route is via $new_gateway on dev $IFACE"
 }
 skip_fixup() {
-	cur_gateway=$(ip -6 route show default | awk '{print $3}')
-	log "rdisc6 not installed, will not send Router Solicitation"
-	log "IPv6 connectivity to WAN may fail or be delayed"
-	[ -z "$cur_gateway" ] && log "no default IPv6 route yet" ||
-		log "default IPv6 route is via $cur_gateway"
+  cur_gateway=$(ip -6 route show default | awk '{print $3}')
+  log "rdisc6 not installed, will not send Router Solicitation"
+  log "IPv6 connectivity to WAN may fail or be delayed"
+  [ -z "$cur_gateway" ] && log "no default IPv6 route yet" ||
+    log "default IPv6 route is via $cur_gateway"
 }
 
 case "$reason" in
-	add|update)
-		replace_global_addr
+  add|update)
+    replace_lan_gua; [ "$BINDWAN" = "yes" ] && add_wan_gua
 
-		# Listen for RAs on WAN, even if IPv6 forwarding is enabled
-		log "accepting Router Advertisements on $IFACE"
-		echo 2 > /proc/sys/net/ipv6/conf/$IFACE/accept_ra
+    # Listen for RAs on WAN, even if IPv6 forwarding is enabled
+    log "accepting Router Advertisements on $IFACE"
+    echo 2 > /proc/sys/net/ipv6/conf/$IFACE/accept_ra
 
-		[ -x "$(which rdisc6)" ] && fixup_default_route || skip_fixup
-	;;
-	delete)
-		log "removing all global IPv6 addresses on LAN interface $LAN"
-		ip -6 addr flush dev $LAN scope global || die "failed"
-		log "removing the default IPv6 route"
-		ip -6 route flush default || die "failed"
-	;;
+    [ -x "$(which rdisc6)" ] && fixup_default_route || skip_fixup
+  ;;
+  delete)
+    msg="removing the default IPv6 route"
+    ip -6 route flush default && log "$msg" 2 || die "$msg"
+    msg="removing all global unicast addresses on LAN interface $LAN"
+    ip -6 addr flush dev $LAN scope global && log "$msg 2" || die "$msg"
+    msg="removing all global unicast addresses on WAN interface $IFACE"
+    ip -6 addr flush dev $WAN scope global && log "$msg 2" || die "$msg"
+
+    # Alternative: remove only the 2600:1700:xxx0:xxx0::1/128 address on WAN
+    # GUA128=$(ip -6 -br addr show dev $IFACE 2>/dev/null)
+    # GUA128=$(echo $GUA128 | grep -o "2600:1700:.*0:.*0::1/128" 2>/dev/null)
+    # [ -z "$GUA128" ] && return
+    # msg="removing $GUA128 on WAN interface $IFACE"
+    # ip -6 addr del $GUA128 dev $IFACE && log "$msg" 2 || die "$msg"
+  ;;
 esac
 
 log "finished"
